Dynamics Group 4 Project/WebApplication/Controllers/MortgageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer.Models;
using WebApplication.Models;
using Microsoft.AspNet.Identity;

namespace WebApplication.Controllers
{
    public class MortgageIndexModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DynamicsId { get; set; }
        public string WebAppId { get; set; }
        public List<MortgageModel> Mortgages { get; set; }
        public List<MortgageCaseModel> Cases { get; set; }
        public List<MortgagePaymentRecordModel> Payments { get; set; }
    }

    [Authorize]
    public class MortgageController : Controller
    {
        //public static SelectList MortgageTermList = new SelectList(
        //    new List<SelectListItem>
        //    {
        //        new SelectListItem { Text = "10 Years", Value = "283210000" },
        //        new SelectListItem { Text = "15 Years", Value = "283210001" },
        //        new SelectListItem { Text = "30 Years", Value = "283210002" },
        //        new SelectListItem { Text = "30 Years", Value = "283210003" }
        //    }, "Value", "Text"
        //);

        //public enum TermEnum { Ten = 283210000, Fifteen = 283210001, Twenty = 283210002, Thirty = 283210003 };

        public static SelectList StatesSelectList = new SelectList(
            new List<SelectListItem>
            {
                new SelectListItem { Text = "Alabama", Value = "Alabama" },
                new SelectListItem { Text = "Alaska", Value = "Alaska" },
                new SelectListItem { Text = "Arizona", Value = "Arizona" },
                new SelectListItem { Text = "Arkansas", Value = "Arkansas" },
                new SelectListItem { Text = "California", Value = "California " },
                new SelectListItem { Text = "Colorado", Value = "Colorado" },
                new SelectListItem { Text = "Connecticut", Value = "Connecticut " },
                new SelectListItem { Text = "Delaware", Value = "Delaware" },
                new SelectListItem { Text = "District of Columbia", Value = "District of Columbia " },
                new SelectListItem { Text = "Florida", Value = "Florida" },
                new SelectListItem { Text = "Georgia", Value = "Georgia" },
                new SelectListItem { Text = "Hawaii", Value = "Hawaii" },
                new SelectListItem { Text = "Idaho", Value = "Idaho" },
                new SelectListItem { Text = "Illinois", Value = "Illinois" },
                new SelectListItem { Text = "Indiana", Value = "Indiana " },
                new SelectListItem { Text = "Iowa", Value = "Iowa" },
                new SelectListItem { Text = "Kansas", Value = "Kansas" },
                new SelectListItem { Text = "Kentucky", Value = "Kentucky" },
                new SelectListItem { Text = "Louisiana", Value = "Louisiana" },
                new SelectListItem { Text = "Maine", Value = "Maine " },
                new SelectListItem { Text = "Maryland", Value = "Maryland " },
                new SelectListItem { Text = "Massachusetts", Value = "Massachusetts " },
                new SelectListItem { Text = "Michigan", Value = "Michigan " },
                new SelectListItem { Text = "Minnesota", Value = "Minnesota" },
                new SelectListItem { Text = "Mississippi", Value = "Mississippi " },
                new SelectListItem { Text = "Missouri", Value = "Missouri " },
                new SelectListItem { Text = "Montana", Value = "Montana" },
                new SelectListItem { Text = "Nebraska", Value = "Nebraska" },
                new SelectListItem { Text = "Nevada", Value = "Nevada" },
                new SelectListItem { Text = "New Hampshire", Value = "New Hampshire" },
                new SelectListItem { Text = "New Jersey", Value = "New Jersey " },
                new SelectListItem { Text = "New Mexico", Value = "New Mexico" },
                new SelectListItem { Text = "New York", Value = "New York" },
                new SelectListItem { Text = "North Carolina", Value = "North Carolina" },
                new SelectListItem { Text = "North Dakota", Value = "North Dakota" },
                new SelectListItem { Text = "Ohio", Value = "Ohio" },
                new SelectListItem { Text = "Oklahoma", Value = "Oklahoma" },
                new SelectListItem { Text = "Oregon", Value = "Oregon" },
                new SelectListItem { Text = "Pennsylvania", Value = "Pennsylvania" },
                new SelectListItem { Text = "Rhode Island", Value = "Rhode Island " },
                new SelectListItem { Text = "South Carolina", Value = "South Carolina " },
                new SelectListItem { Text = "South Dakota", Value = "South Dakota" },
                new SelectListItem { Text = "Tennessee", Value = "Tennessee" },
                new SelectListItem { Text = "Texas", Value = "Texas" },
                new SelectListItem { Text = "Utah", Value = "Utah" },
                new SelectListItem { Text = "Vermont", Value = "Vermont" },
                new SelectListItem { Text = "Virginia", Value = "Virginia" },
                new SelectListItem { Text = "Washington", Value = "Washington" },
                new SelectListItem { Text = "West Virginia", Value = "West Virginia " },
                new SelectListItem { Text = "Wisconsin", Value = "Wisconsin" },
                new SelectListItem { Text = "Wyoming", Value = "Wyoming" }
            }, "Value", "Text"
        );

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: User
        public ActionResult Index()
        {
            //return View(db.UserMapModels.ToList());
            MortgageIndexModel mortgageIndexModel = new MortgageIndexModel();
            try
            {
                using (var context = new ApplicationDbContext())
                {
                    Guid userId = new Guid(User.Identity.GetUserId());
                    var user = (from u in context.UserMapModels
                                where u.UserWebAppId == userId
                                select u).ToList()[0];

                    mortgageIndexModel.FirstName =  user.FirstName;
                    mortgageIndexModel.LastName =   user.LastName;
                    mortgageIndexModel.DynamicsId = user.ClientDynamicsId.ToString();
                    mortgageIndexModel.WebAppId =   user.UserWebAppId.ToString();
                    mortgageIndexModel.Cases = DataAccessLayer.DynamicsDB.GetCases(user.ClientDynamicsId);
                    mortgageIndexModel.Mortgages = DataAccessLayer.DynamicsDB.GetMortgages(user.ClientDynamicsId);
                    mortgageIndexModel.Payments = DataAccessLayer.DynamicsDB.GetPayments(mortgageIndexModel.Mortgages);
                }
            }
            catch(Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"MortgageController Index threw: {ex.Message}\n{ex.StackTrace}");
            }
            ViewBag.Title = $"{User.Identity.Name}";
            return View(mortgageIndexModel);
        }

        // GET: User/Create
        public ActionResult CreateCase()
        {
            List<SelectListItem> UserMortgages = new List<SelectListItem>();
            List<MortgageModel> Mortgages = new List<MortgageModel>();
            try
            {
                using (var context = new ApplicationDbContext())
                {
                    Guid userId = new Guid(User.Identity.GetUserId());
                    var user = (from u in context.UserMapModels
                                where u.UserWebAppId == userId
                                select u).ToList()[0];

                    Mortgages = DataAccessLayer.DynamicsDB.GetMortgages(user.ClientDynamicsId);
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"MortgageController CreateCase threw: {ex.Message}\n{ex.StackTrace}");
            }
            foreach(MortgageModel m in Mortgages)
            {
                UserMortgages.Add(new SelectListItem { Text = $"{m.Name} ({m.MortgageNumber})", Value = m.MortgageId.ToString() });
            }

            ViewBag.UserMortgages = new SelectList(UserMortgages, "Value", "Text");
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCase([Bind(Include = "MortgageId,Title,Description,Priority,HighPriorityReason,Type")] MortgageCaseModel caseModel)
        {
            if (ModelState.IsValid)
            {
                using (var context = new ApplicationDbContext())
                {
                    Guid userId = new Guid(User.Identity.GetUserId());
                    caseModel.ContactId = (from u in context.UserMapModels
                                           where u.UserWebAppId == userId
                                           select u).ToList()[0].ClientDynamicsId;
                }
                DataAccessLayer.DynamicsDB.CreateCase(caseModel);
                return RedirectToAction("Index");
            }

            List<SelectListItem> UserMortgages = new List<SelectListItem>();
            List<MortgageModel> Mortgages = new List<MortgageModel>();
            try
            {
                using (var context = new ApplicationDbContext())
                {
                    Guid userId = new Guid(User.Identity.GetUserId());
                    var user = (from u in context.UserMapModels
                                where u.UserWebAppId == userId
                                select u).ToList()[0];

Dynamics Group 4 Project/WebApplication/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer.Models;
using WebApplication.Models;
using Microsoft.AspNet.Identity;

namespace WebApplication.Controllers
{
    public class SupportController : Controller
    {
        public ActionResult Article(string article)
        {
            String f = HttpContext.Server.MapPath("~/Views/Support/" + article + ".cshtml");
            if (System.IO.File.Exists(f))
                ViewBag.ArticleContent = article;
            else
                ViewBag.ArticleContent = "_Error";

            return View();
        }
    }
}

Dynamics Group 4 Project/WebApplication/Views/Support/Article.cshtml
@{
    string articleContent = "";
    if (ViewBag.ArticleContent != null)
    {
        articleContent = ViewBag.ArticleContent.ToString();
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
    <!-- SEARCH FIELD AREA -->
    <div class="searchfield bg-hed-six">
        <div class="container" style="padding-top: 20px; padding-bottom: 20px;">
            <div class="row text-center margin-bottom-20">
                <h2 class="white"> Support Articles </h2>
            </div>
            <hr />
        </div>
    </div>
    <!-- END SEARCH FIELD AREA -->
    <!-- MAIN SECTION -->
    <div class="container featured-area-default padding-30">
        <div class="row">
            <div class="col-md-8 padding-20">
                <div class="row">
                    @if (articleContent != "")
                    {
                        @Html.Partial(articleContent)
                    }
                </div>
            </div>
            <!-- SIDEBAR -->
            <div class="col-md-4 padding-20">
                <div class="row margin-top-20">
                    <div class="col-md-12">
                        <h2>Similar Articles</h2>
                        <hr class="style-three">
                        <div class="padding-left-10">
                            <ul>
                                <li> @Html.ActionLink("Applying for a Mortgage", "Article", "Support", new { article = "_MortgageApply" }, null) </li>
                                <li> @Html.ActionLink("Viewing your Mortgages", "Article", "Support", new { article = "_MortgageView" }, null) </li>
                                <li> @Html.ActionLink("Reporting an Incident", "Article", "Support", new { article = "_IncidentReport" }, null) </li>
                                <li> @Html.ActionLink("Viewing Reported Incidents", "Article", "Support", new { article = "_IncidentView" }, null) </li>
                                <li> @Html.ActionLink("Make a Payment", "Article", "Support", new { article = "_MakePayment" }, null) </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row margin-bottom-30">
                    <div class="col-md-12 ">
                        <div class="support-container">
                            <h2 class="support-heading">Need more Support?</h2>
                            If you cannot find an answer in the knowledgebase, you can
                            @Html.ActionLink("contact us", "Index", "Home", new {  }, null) for further help.
                        </div>
                    </div>
                </div>
                <hr />
            </div>
            <!-- END SIDEBAR STUFF -->
        </div>
    </div>
    <!-- END MAIN SECTION -->
</body>
</html>

Dynamics Group 4 Project/WebApplication/Views/Support/_Error.cshtml
<h4> An article with that name does not exist! </h4>
                

Dynamics Group 4 Project/WebApplication/Views/Support/_IncidentReport.cshtml
<h3>How to Report an Incident:</h3>
<ol>
    <li> Login to your account at @Html.ActionLink("Contoso Mortgages", "Index", "Home", new { }, null). </li>
    <li> Along the website's main menu bar located at the top of page, select @Html.ActionLink("Report Incident", "CreateCase", "Mortgage", new { }, null) . </li>
    <li> Incident Report Fields: </li>
    <ol>
        <li> <b>Mortgage</b>: Select an existing Mortgage this Incident applies to. </li>
        <li> <b>Title</b>: The Incident's title can be anything you like that helps to generally describe the Incident. </li>
        <li> <b>Description</b>: A more detailed description of the Incident. </li>
        <li> <b>Priority</b>: Specify 'High', 'Normal', or 'Low' to denote the urgency of the incident. </li>
        <li> <b>High Priority Reason</b>: This field only appears if you selected 'High' as the Priority level. This field is meant to be the rationale for this incident being a high priority. </li>
        <li> <b>Type</b>: Specify the type of the incident </li>
    </ol>
</ol>

Dynamics Group 4 Project/WebApplication/Views/Support/_IncidentView.cshtml
<h3>How to View your Reported Incidents:</h3>
<ol>
    <li> Login to your account at @Html.ActionLink("Contoso Mortgages", "Index", "Home", new { }, null). </li>
    <li> Along the website's main menu bar located at the top of page, select @Html.ActionLink("My Account", "Index", "Mortgage", new { }, null) . </li>
    <li> A list of your reported Incidents and their respective information are listed under "Cases". </li>
</ol>
                

Dynamics Group 4 Project/WebApplication/Views/Support/_MakePayment.cshtml
<h3>How to View your Reported Incidents:</h3>
<ol>
    <li> Login to your account at @Html.ActionLink("Contoso Mortgages", "Index", "Home", new { }, null). </li>
    <li> Along the website's main menu bar located at the top of page, select @Html.ActionLink("My Account", "Index", "Mortgage", new { }, null) . </li>
    <li> A list of your next payments for each of your mortgages and their respective information are listed under "Upcoming Payments". </li>
    <li> The payment information tells you which mortgage it applies to, the amount owed, and the due date. </li>
    <li> You can make a payment by clicking the "Pay Now" button for the corresponding payment. </li>
</ol>
               

Dynamics Group 4 Project/WebApplication/Views/Support/_MortgageApply.cshtml
<h3>How to Apply for a Mortgage:</h3>
<ol>
    <li> Login to your account at @Html.ActionLink("Contoso Mortgages", "Index", "Home", new { }, null). </li>
    <li> Along the website's main menu bar located at the top of page, select @Html.ActionLink("Apply for Mortgage", "NewMortgage", "Mortgage", new { }, null) . </li>
    <li> Mortgage Fields: </li>
    <ol>
        <li> <b>Name</b>: The name can be anything you like that helps you reference the mortgage. </li>
        <li> <b>Region</b>: Specify the region in which you live. </li>
        <li> <b>State</b>: This field only appears if you selected 'US' as the region. If you live in the US, please specify which State you live in. </li>
        <li> <b>Amount</b>: Specify the mortgage amount in US Dollars. </li>
        <li> <b>Term (Years)</b>: Specify the term of the mortgage, the options are 10, 15, 20, and 30 year mortgages. </li>
    </ol>
</ol>
              

Dynamics Group 4 Project/WebApplication/Views/Support/_MortgageView.cshtml
<h3>How to View your Reported Incidents:</h3>
<ol>
    <li> Login to your account at @Html.ActionLink("Contoso Mortgages", "Index", "Home", new { }, null). </li>
    <li> Along the website's main menu bar located at the top of page, select @Html.ActionLink("My Account", "Index", "Mortgage", new { }, null) . </li>
    <li> A list of your Mortgages and their respective information are listed under "Mortgages". </li>
</ol>